version: '3'
services:
  streamlit:
    build:
      context: ./API
      dockerfile: ../dockerfile
    ports:
      - 8000:8000
  uvicorn:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8001:8000
