version: '3'

services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8501:8501
    restart: always

  uvicorn:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:8000
    restart: always
